---
- name: Assert SECRET_KEY is available and not empty
  ansible.builtin.assert:
    that:
      - outline_docker_outline_secret_key is defined
      - outline_docker_outline_secret_key | length > 0
    fail_msg: Generate a hex-encoded 32-byte random key. You should use `openssl rand -hex 32`.

- name: Assert UTILS_SECRET is available and not empty
  ansible.builtin.assert:
    that:
      - outline_docker_outline_utils_key is defined
      - outline_docker_outline_utils_key | length > 0
    fail_msg: Generate a unique random key. The format is not important but you could still use `openssl rand -hex 32`.

- name: Assert POSTGRES_PASSWORD is available and not empty
  ansible.builtin.assert:
    that:
      - outline_docker_postgres_password is defined
      - outline_docker_postgres_password | length > 0
    fail_msg: You should set a password for the postgresql database.
